name: Step 3, Upload test reports

# This workflow triggers when pushing the ci.yml file to the ci branch or manually
on:
  workflow_dispatch:
  push:
    branches:
      - ci
    paths:
      - .github/workflows/ci.yml

permissions:
  contents: write

jobs:
  # Job 1: Check current step number
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  # Job 2: Update step from 3 to 4 if conditions met
  on_add_test_reporting:
    name: On add test reporting
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 3 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Verify workflow
        uses: skills/action-check-file@v1
        with:
          file: .github/workflows/ci.yml
          search: actions/upload-artifact
      - name: Update to step 4
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
          branch_name: ci

  # Job 3: Build and lint markdown, upload report
  build:
    name: Build and Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json 2> remark-lint-report.json

      - name: Upload remark lint report
        uses: actions/upload-artifact@v4
        with:
          name: remark-lint-report
          path: remark-lint-report.json

